export * from "./HomePage/HomePage";
export * from "./LoginPage/LoginPage";
export * from "./TasksPage/TasksPage";
export * from "./DevicePage/DevicePage";
export * from "./CreateDevicePage/CreateDevicePage";
export * from "./StatusTaskPage/StatusTaskPage"
export * from "./ProjectPage/ProjectPage"
export * from "./CreateProjectPage/CreateProjectPage"
export * from "./CreateStatusPage/CreateStatusPage"
